name: Deploy add-to-cart to EC2 (main)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/add-to-cart:latest .

    - name: Push image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/add-to-cart:latest

    - name: SSH & deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          if ! command -v docker &> /dev/null
          then
            echo "🔧 Instalando Docker..."
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
          fi

          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/add-to-cart:latest

          # Detener y eliminar contenedor previo si existe
          sudo docker stop add-to-cart || true
          sudo docker rm add-to-cart || true

          sudo docker run -d \
            --name add-to-cart \
            --restart=always \
            -p 8000:8000 \
            ${{ secrets.DOCKERHUB_USERNAME }}/add-to-cart:latest